### ISSUE TITLE
Add a way to see expanded macros

### ISSUE THREAD

**Issue by Diggsey** [integer32llc/rust-playground#158]
There's currently no way to experiment with `macro_rules` online. I think having a `--pretty=expanded` option on the playground would be great.

**Comment by shepmaster** [comment]
An interesting idea! Is that a stable flag, do you know? 

Any suggestions or hastily mocked-up drawings for how this could fit in the UI?

**Comment by Diggsey** [comment]
It's an unstable flag.

I imagine it could sit within the `tools` group, and act similarly to `Format`. (You can therefore use "undo" to un-expand the macros).

It's probably worth running it through the formatter as part of the expansion, or maybe use `cargo-expand` which does this already.

**Comment by joshtriplett** [comment]
I'd really like to see this as well.

@shepmaster This should sit next to Clippy, and open another output tab labeled "Expanded Macros" or similar. I don't think it makes sense to change the original code; this should be an output format. For a first pass, it can just dump the output directly into an output tab. As a second pass, it'd be *incredible* to have a diff-like mechanism that lets you move through the code on the left and highlight the corresponding expanded span on the right. The compiler has that information; you'd just need to dump it and turn it into JSON to hand to the client.

**Comment by joshtriplett** [comment]
https://github.com/rust-lang/rust/issues/43364

**Comment by tomwhoiscontrary** [comment]
I was looking for this feature just now. The first place i looked was in the "WHAT DO YOU WANT TO DO?" menu next to the build button, because macro-expanded pseudo-source feels like a kind of intermediate output, like MIR or LLVM IR. The second place i looked was in the "Tools" menu, because that's where random useful things live. The playground's UI is small enough that people will probably find it soon enough, wherever it is!

From the discussion on rust-lang/rust#43364, it sounds like the rustc flag won't be stabilised any time soon. Could this be an option which only works on nightly? I wouldn't mind that.

About formatting, the discussion on rust-lang/rust#43364 includes a comment about "an issue where a macro expansion results in unparseable output". So perhaps it's unwise to assume that the output can always be formatted, and either not format it at all, or handle failure, or make it optional.

**Comment by peterjoel** [comment]
It would be useful even it it was just an "Expand Macros" option under "Tools", which create a tab in the right pane, with unformatted text in it.

**Comment by spease** [comment]
I'd also like to see this, I believe it'd be useful for derives

**Comment by nagisa** [comment]
Wanted.

**Comment by Flowneee** [comment]
@shepmaster I attempted to implement this feature in #599. It currently very simple and don't include any option to format output, also rely on nightly compiler.

**Comment by shepmaster** [comment]
Closed via #599

**Comment by tomwhoiscontrary** [comment]
@Flowneee Fantastic, thank you!
