### ISSUE TITLE
There should be a way to tell the exact compiler version.

### ISSUE THREAD

**Issue by kennytm** [integer32llc/rust-playground#184]
Expose `rustc -vV`, which can tell you Stable is `1.19.0`, Beta is `1.20.0-beta.1`, Nightly is `1.20.0-nightly (ae98ebfcb 2017-07-20)`. 

Currently these can only be retrieved by triggering an ICE, which is very inconvenient.

**Comment by shepmaster** [comment]
> only be retrieved by triggering an ICE

```rust
fn main() {
    println!("{:?}", std::process::Command::new("rustc").arg("-vV").output());
}
```

**Comment by kennytm** [comment]
@shepmaster thanks. Still inconvenient 😝

**Comment by shepmaster** [comment]
Yep. Do you have a vision of how this information would be presented? I'd like to also eventually show the available crates and their versions, so this type of metadata might want a bit of a home.

**Comment by kennytm** [comment]
Adding a "Versions" button to show the versions of the current toolset should be good enough.

![screenshot_2017-07-26 23 28 52_81jcma-fs8](https://user-images.githubusercontent.com/103023/28630305-8b87d42e-725c-11e7-9e83-55477f231626.png)

**Comment by shepmaster** [comment]
Massive props for the thorough mockup! Also, I'm glad you included the clippy / rustfmt versions — I had completely forgotten about them.

I like the idea of having a link to the crate - were you thinking that would go to the crates.io page or somewhere else?

> Adding a "Versions" button to show the versions of the current toolset should be good enough.

I'm very hesitant to add more buttons to the current header. They are already so many that a reasonable-sized window cuts them off. Simply wrapping doesn't really help because then the main reason you are on the page (the editor and output fields) get even less space.

I've got some back-of-mind ideas that I'm mulling about. Maybe other people will chime in with some ideas.

**Comment by kennytm** [comment]
> were you thinking that would go to the crates.io page or somewhere else?

I prefer docs.rs

**Comment by shepmaster** [comment]
#219 introduces a bare-bones solution:

![image](https://user-images.githubusercontent.com/174509/32001240-35e03244-b967-11e7-88a9-4a5e4b251a55.png)

**Comment by shepmaster** [comment]
Ok, the changes in #299 give a place for these:

![image](https://user-images.githubusercontent.com/174509/39072931-16e0d5fe-44ba-11e8-860e-9bee155ac5bb.png)

I've opened #300 and #301 for the related parts.
