### ISSUE TITLE
Auto indentation and adding of closing braces

### ISSUE THREAD

**Issue by mikeyhew** [integer32llc/rust-playground#202]
The old Rust playground used to auto-indent and add a closing `}` when you typed `{` and hit enter. I liked that. Could that feature be added?

**Comment by shepmaster** [comment]
There's a bug / ugliness in the version of Ace we are using (1.2.6) around auto-pairing of <kbd>'</kbd>, which is super annoying for lifetimes. You can see that the old playground had to [work around this behavior](https://github.com/rust-lang/rust-playpen/blob/7c04bc3a48c2273c78428b17daa7a3be52ab319f/static/web.js#L744-L778). We [chose to disable the whole shebang](https://github.com/integer32llc/rust-playground/blob/707e78a8faafe9e1369d50db7d5740ab3193b6e2/ui/frontend/AdvancedEditor.jsx#L70-L72) instead (since a previous version didn't have it anyway).

Ace has [fixed this in 1.2.7](https://github.com/ajaxorg/ace/commit/371f73ba2cded804c8fa828d822e320f68c61ff5), but the brace package is still on 1.2.6. They would like to [upgrade to 1.2.8](https://github.com/thlorenz/brace/pull/93), but are blocked on a rogue `debugger` statement added in that release.

**Comment by mikeyhew** [comment]
Awesome 🎉
