### ISSUE TITLE
Add 'failure' crate which is to become the new std way of handling errors

### ISSUE THREAD

**Issue by rusterize** [integer32llc/rust-playground#255]
The `failure` crate is posed to become the new standard way to handle errors, replacing error-chain. This is one crate where the "most downloaded" algorithm doesn't really apply at this point due to the fact that it is new and  the intention  is for it to replace std::error::Error; could you please add it to the playground.

**Comment by shepmaster** [comment]
No.

As you read in the Github UI before submitting this issue:

> If you are requesting that a specific crate be added, please review [our policy](https://github.com/integer32llc/rust-playground/issues/101) about which crates are accepted. TL;DR: we don't currently accept one-off additions of crates.

The top 100 popular crates (ranked by all-time downloads), crates that are part of the Rust Cookbook and all of their dependencies are available for use.

I **will not** be unilaterally deciding that a given crate will be the future savior of Rust-kind. If a crate is useful, then it will be used. If it is used, it will show up on the playground eventually. If you think that future is the One True error handling solution, then submit a PR to one of the top X crates to replace error-chain with it. Then it will be available.

**Comment by eminence** [comment]
In addition to the top 100 crates ranked by all-time downloads, would you also consider the top crates as measured by downloads in the past year?   As time goes on, it will be come harder-and-harder for new crates to break into the top-100-all-time category, because they have to compete with crates that have been around for years.  

(There may not be an API to get this information, but I'm wondering if you would agree in principle)

**Comment by shepmaster** [comment]
@eminence please feel free to follow the [link in my previous comment](https://github.com/integer32llc/rust-playground/issues/101) which leads to an issue discussing alternate ways of calculating the top crates. Remember that *every* algorithm is going to make someone unhappy.
