### ISSUE TITLE
The new menu is blurred in the current version

### ISSUE THREAD

**Issue by pravic** [integer32llc/rust-playground#303]
… on Chrome-based browsers (Chrome, Vivaldi, etc.) on Windows.

Not to mention that it requires more clicks to access something :angry: 

![image](https://user-images.githubusercontent.com/724639/39082665-92474a8e-455f-11e8-8085-4512ec9d7b8b.png)

**Comment by lqd** [comment]
@pravic What is your software and hardware configuration ? 

It isn't blurry in Chrome on the machines I tested with, on osx or windows, on non-retina screens. (It isn't blurry on my iOS retina screens either, on iPhone or iPad, but that's Webkit).
There are no effects or shadows or anything that comes to mind on this specific text that would make it blurry, strange. I'll need to look into how to reproduce this.

@shepmaster btw are you able to reproduce this in Chrome on Retina screens ?

**Comment by shepmaster** [comment]
> because chrome often disables subpixel antialiasing for elements with these properties

Hmm, thanks! Any idea why it would be disabled in one place (the original reporter) and not others (mine)?

**Comment by shepmaster** [comment]
Oh, and since you are here, @nightwing, **thank you very much** for your work on Ace! This Playground would be a lot worse without it! 💚

**Comment by lqd** [comment]
@nightwing — the hero we needed :)

**Comment by nightwing** [comment]
@shepmaster the issue only happens on windows, and the amount of blurriness depends on cleartype configuration. 
Mac doesn't have this problem because retina screens have enough resolution to not care much about subpixel antialiasing, and on linux versions that i have tried, subpixel antialiasing does not work without transform either.

We had to deal with this same issue in Ace recently https://github.com/ajaxorg/ace/pull/3623/commits/73d9a511c3fcc1a1ce13bf69c15afc641cfcd445 

> This Playground would be a lot worse without it!

Thank you for kind words! Ace itself would be a lot worse without bug reports and feature requests from the community.
