### ISSUE TITLE
Permalink mode and channel are undefined when loaded from the permalink

### ISSUE THREAD

**Issue by sgrif** [integer32llc/rust-playground#316]
Generating a permalink to some code on the playground currently has "version=undefined&mode=undefined" in the query string. This happens even if you have specified a version other than stable, or a mode other than debug. This seems to have been caused by the new design

**Comment by shepmaster** [comment]
> This seems to have been caused by the new design

What are you basing that on?

**Comment by shepmaster** [comment]
Can you add some steps to reproduce? I'm not seeing it:

![linking](https://user-images.githubusercontent.com/174509/39335292-66212518-4980-11e8-988f-4b06657473f1.gif)

**Comment by sgrif** [comment]
> What are you basing that on?

The fact that I noticed the redesign for the first time when I noticed this issue. It's entirely unrelated.

> Can you add some steps to reproduce? I'm not seeing it:

Based on your gif.... no. :(

And actually I can't even reproduce it now. So I'm going to just straight up assume this was all a dream. I'm blaming Vivian.

**Comment by shepmaster** [comment]
> I'm blaming Vivian.

👶

**Comment by trentj** [comment]
I came across this earlier today, and chanced to figure out how to reproduce it.

All you have to do is follow the link twice. After clicking "Share", click the permalink. Once the page loads again, you still see a permalink in the right-half (or bottom) pane, but it has "version=undefined&mode=undefined" instead of the proper values.

It was different before the redesign to the best of my recollection.

**Comment by shepmaster** [comment]
As an aside, it's like 99%  unlikely that the redesign had anything to do with this. However, it doesn't matter because it's a bug now.
