### ISSUE TITLE
Cursor jumped to the end of main function

### ISSUE THREAD

**Issue by masahiko-ofgp** [integer32llc/rust-playground#494]
is as: 
When a line break, the cursor jumped to the end of `main`

    fn main() {
        let x = 5;  <---- Return
    } <<=== cursor jumped here

It used to work without this problem before.

to be:
    
    fn main() {
        let x = 5;  <---- Return
        <<=== cursor 
    }

environment:

ManjaroLinux Firefox 67.0

**Comment by mikeyhew** [comment]
This also happens in Chrome, and here is another case where this happens: starting from a blank editor, type `fn main() {`, then hit enter - you will be automatically indented 4 spaces in and a closing curly brace `}` will be added below. Then type anything, and hit ctrl-Z. The text you typed will have random characters removed and the cursor will be moved to the very bottom right, after the `}`.


![ezgif-2-2ea6a90aecc2](https://user-images.githubusercontent.com/6751033/58759455-48399580-84f8-11e9-9ccb-78b8de1986d5.gif)

**Comment by kennytm** [comment]
Probably caused by #493.

**Comment by Stargateur** [comment]
when you type too fast letter this happen, it's also work for copy paste, when you past you cursor jump

**Comment by shepmaster** [comment]
Here's what I think is happening:

- Inside of curly braces, Ace auto-indents for us
- When you hit <kbd>return</kbd>, two change events are generated
  1. Adding the newline
  1. Adding the indentation
- Because of the Redux architecture, both of those changes flow back into the editor
- Before applying the changes, we check to see if anything will actually change. 
- Ace internally applies both of the changes before the first one goes through the circle and is "reapplied"

There are at least two issues here:

1. We weren't properly preserving the cursor position when updating the content (fixed by #495)
1. We are processing more change events than we strictly need to.

I'm not sure if there's an Ace setting to coalesce the user-supplied changes (typing) with the editor-supplied changes (auto-indentation). While I look into that, I'm going to try some simple debouncing techniques to reduce the frequency of such events.

**Comment by shepmaster** [comment]
See also #497

**Comment by shepmaster** [comment]
For people still experiencing issues, the playground has aggressive 24-hour caching; a hard reload in your browser should get the newest files.

**Comment by masahiko-ofgp** [comment]
Gratitude for the quick response.

2019年6月3日(月) 1:25 Jake Goulding <notifications@github.com>:

**Comment by shepmaster** [comment]
Thank you for the bug report, and sorry for any inconvenience!

**Comment by masahiko-ofgp** [comment]
No problem. Playground is always very useful :)

2019年6月3日(月) 11:05 Jake Goulding <notifications@github.com>:
