### ISSUE TITLE
Nightly (and Miri, Clippy, Rustfmt) are not updating

### ISSUE THREAD

**Issue by lzutao** [integer32llc/rust-playground#504]
The latest rustfmt version is rustfmt 1.3.0-nightly (d334502 2019-06-09).
Although I tried to change rust channel, the rustfmt version is still 
2019-04-24 5274b49.

**Comment by shepmaster** [comment]
> The latest rustfmt version is rustfmt 1.3.0-nightly

This is likely just a side-effect of the fact that [the nightly channel doesn’t build at the moment](https://travis-ci.com/integer32llc/rust-playground/jobs/210146951) due to an [issue in Cargo](https://github.com/rust-lang/cargo/issues/7049) caused by an issue in [libgit2](https://github.com/libgit2/libgit2/issues/5130).

Once nightly updates, rustfmt should be updated automatically:

```
$ rustc --version
rustc 1.37.0-nightly (7cdaffd79 2019-06-05)
$ rustfmt --version
rustfmt 1.2.2-nightly (5274b49c 2019-04-24)

$ rustup update
…

$ rustc --version
rustc 1.37.0-nightly (929b48ec9 2019-06-21)
$ rustfmt --version
rustfmt 1.3.0-nightly (d3345024 2019-06-09)
```

**Comment by lzutao** [comment]
Ah thanks for letting me know. I heard about that cargo issue but
didn't think that this issue and that one had a connection.
You could close this issue if you like.

**Comment by shepmaster** [comment]
Might as well wait until it’s cleared up somehow and make sure that things are updated. I also [manually triggered](https://travis-ci.com/integer32llc/rust-playground/jobs/210146952) the rustfmt container as a way of seeing if it will update (gotta wait for it to deploy though)
