### ISSUE TITLE
nom 5.0.1 update

### ISSUE THREAD

**Issue by tanriol** [integer32llc/rust-playground#538]
Please consider updating `nom` to nom 5 series. It's been stable since Jun 24 and, since this is a significant shift in idioms, nom 4 support available now is only useful for people who are still writing code in nom 4 without migrating to nom 5.

**Comment by shepmaster** [comment]
nom is not one of the top 100 crates and is only included on the playground because it's a dependency for some other crate:

```
nom v4.2.3
└── weedle v0.10.0
    └── wasm-bindgen-webidl v0.2.51
        [build-dependencies]
        └── web-sys v0.3.28
```

As such, we only build the version of nom that is required. It's only exposed because we had to build it anyway. If you'd like the current version of nom to be present, you will need to either

1. Change [weedle](https://crates.io/crates/weedle) (and any requisite upstream users) to upgrade to nom5
1. Petition the [Rust cookbook](https://rust-lang-nursery.github.io/rust-cookbook/) to include nom
