### ISSUE TITLE
Line number column is not fixed-width

### ISSUE THREAD

**Issue by cbreeden** [integer32llc/rust-playground#54]
A concern by a user mentioned that it bothered them that the line number column is not fixed width.  You can see this by opening a blank editor, and hitting enter.  You will notice that the width of the line number column increases going from line 9 -> line 10, and from line 99 -> line 100.

**Comment by shepmaster** [comment]
This one might be difficult. The width actually [changes as you scroll](http://feedback.codebender.cc/forums/165703-general-requests/suggestions/7817235-base-the-width-of-the-line-number-gutter-on-the-nu), not based on the number of lines. There's also the problem that you can always add more lines; should the fixed width handle 99999999 lines (and if so, what should happen when you add one more)?

**Comment by cbreeden** [comment]
Indeed, I don't know.  Perhaps you can keep the width fixed until you hit 1000 (i think the default width can fit 999) and then change the width?  Don't know if there is a good solution for this or not.  What does VIM, VSCode and others do I wonder.

**Comment by BGR360** [comment]
This problem persists, and it causes the entire text area to shift right and left when the maximum visible line number gains or loses a digit. It's pretty disorienting.

I traced the problem back to the `ace` library and filed an issue there: https://github.com/ajaxorg/ace/issues/4565. If they fix it, please update the version of `ace` you're using.

**Comment by BGR360** [comment]
Turns out there's already a feature in ace to get the behavior I'm asking for: `fixedWidthGutter`.

Instructions according to https://github.com/ajaxorg/ace/issues/4565#issuecomment-925317401:
> it  can be used with
   editor.setOption("fixedWidthGutter", true)
or by passing options object ot ace.edit like this
   ace.edit(domNode, {"fixedWidthGutter", true})

@shepmaster sorry for the false alarm on it being an upstream problem. Think you could add this flag to the ace editor used in the playground?
