### ISSUE TITLE
Lifetime annotation on main() doesn't give error E0131

### ISSUE THREAD

**Issue by gaveen** [integer32llc/rust-playground#618]
Trying to use a lifetime annotation on main() - e.g., `fn main<'a>() {}` should give the error E0131 as in `rustc`. However, what's shown is only a warning: `"function is never used: 'main'"`.

**Comment by shepmaster** [comment]
Since that's not a valid `main` function (as the error points out), the playground doesn't detect it as such. When there's no `main`, the playground defaults to compiling your code as a library:

![image](https://user-images.githubusercontent.com/174509/87104038-bfc21400-c224-11ea-94f3-e1cb414768a0.png)

If you force to to be run:

![image](https://user-images.githubusercontent.com/174509/87104110-eaac6800-c224-11ea-8074-c0c0f2b7747d.png)

You'll see the appropriate error.
