### ISSUE TITLE
When opening a link with a `code` get parameter the 2015 edition is selected

### ISSUE THREAD

**Issue by miDeb** [integer32llc/rust-playground#699]
Example:
https://play.rust-lang.org/?code=use%20rayon%3B%0A%0Afn%20main()%20%7B%0A%20%20%20%20%2F%2F%20try%20using%20the%20%60rayon%60%20crate%20here%0A%7D
(taken from https://crates.io/crates/rayon, "Try on Rust Playground") opens with edition 2015 selected, and the code does not compile due to that.

**Comment by shepmaster** [comment]
Yep, that’s by design. The edition parameter didn’t exist when the playground first started allowing links, so for backwards compatibility it needs to default to 2015, just like Cargo. 

If we defaulted to 2018 now, then various things would break when 2021 became the default. 

The correct solution is to specify which edition you want in the original link.
